spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://106.15.196.61:3306/back_stage?serverTimezone=Shanghai&useUnicode=true&characterEncoding=utf8&useSSL=false
    username: backstagedemo
    password: demo123456





server:
  port: 8080
#  servlet:
#    context-path: /wechat
#  tomcat:
#    uri-encoding: UTF-8
#    max-threads: 1000